image: ubuntu:22.04

stages:
  - build

flatpak:
  stage: build
  tags:
    - docker-sandboxed
    - linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    FLATPAK_BUILDER_NO_USER_CHROOT: "1"
  rules:
    - when: manual
  hooks:
    pre_get_sources_script:
      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git wget
      - wget -O /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
      - chmod +x /usr/local/bin/gitlab-runner
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y flatpak flatpak-builder elfutils build-essential
    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install --user -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08
  script:
    - flatpak-builder --user --disable-rofiles-fuse --force-clean --ccache build-dir com.mooinglemur.axolotl.yml
    - flatpak build-export repo build-dir
    - flatpak build-bundle repo axolotl-apclient.flatpak com.mooinglemur.axolotl
  artifacts:
    name: "axolotl-apclient-flatpak"
    expire_in: 1 week
    paths:
      - axolotl-apclient.flatpak

appimage:
  stage: build
  tags:
    - docker
    - linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - when: manual
  hooks:
    pre_get_sources_script:
      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y cmake ninja-build build-essential libgl1-mesa-dev libfontconfig1-dev libglfw3-dev nlohmann-json3-dev libyaml-cpp-dev libssl-dev git wget file
    - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    - chmod +x linuxdeploy-x86_64.AppImage
  script:
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - ninja
    - DESTDIR=appdir ninja install
    - cd ..
    - export EXCLUDE_LIBS="libssl.so.3;libcrypto.so.3;libssl.so.1.1;libcrypto.so.1.1"
    - ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir build/appdir --executable build/appdir/usr/local/bin/axolotl-apclient --desktop-file axolotl.desktop --icon-file axolotl.png --output appimage
  artifacts:
    name: "axolotl-apclient-appimage"
    expire_in: 1 week
    paths:
      - "*.AppImage"
